### ISSUE TITLE
Multi-domain certs break with DNS slaves

### ISSUE THREAD

**Issue by HeavyThumper** [robin-thoni/certbot-pdns#1]
First - I have to say this is a super incredible wonderful terrific bit of code!  But I've got one little issue...

I have a cert for my mail server, which has three hostnames (smtp, imap, mail).  So that means three DNS entries.  As a result, when running a renewal for my mailserver - this certification plugin gets asked to prepare for three challenges.  This it does...one at a time.  Both watching the interactive client and viewing the logs show this.  If I had a single DNS server, or control over the slaves, then this might work.  But...I'm using BuddyNS.com.  Replication is triggered by a change in the SOA record - which of course this program does fine.  But...this authenticator triggers an update after each challenge is prepared.  Which means add the authentication TXT record, increment SOA, add TXT record, increment SOA, add TXT record...you see where this is going.

So that's three updates.  Which means the slave DNS servers need to update themselves three times in succession - which might get throttled by the remotes.  Especially since I have no control over them.  So what would be magical would be to have the SOA record get updated once - after all the TXT records have been done.

As a stopgap, setting "axfr-time" to 120 appears to be functional.  Just not elegant.

**Comment by robin-thoni** [comment]
Thanks for your support!

I like your request, this seems pretty useful!

I made some changes on a dev branch. Can you clone https://git.rthoni.com/robin.thoni/certbot-pdns and checkout `develop-issue1` and see if this is what you want?

In summary, each zone will be notified only once, and the axfr sleep is done only once for all zone, instead of notifying each zone multiple times and sleeping for each zone.

**Comment by HeavyThumper** [comment]
It works perfectly! Thanks!

**Comment by robin-thoni** [comment]
I just released the new version to the github master branch and on pip
